# Generated by Django 2.2.3 on 2019-07-12 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(default=None, null=True, upload_to='images/')),
                ('top_priority', models.BooleanField(default=False)),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
