# Generated by Django 2.2.3 on 2019-07-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='picture',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
